## DATOS: 
- (P6040) CUANTOS AÑOS CUMPLIDOS TIENE
- (P6050) CUAL ES EL PARENTESCO DE... CON EL JEFE O JEFA DEL HOGAR
- (P3041) LA INSTITUCION A LA QUE ASISTE
-

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

DIRECTORIO DE TRABAJO ACTUAL

In [3]:
current_working_directory = Path.cwd()
current_working_directory

PosixPath('/workspaces/ANALISIS-DE-DATOS-UQ')

In [4]:
#Caracteristicas generales, seguridad social en salud y educacion
#Links a los conjuntos de datos
url_cgsse = 'https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV'
url_ocupados ='https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
url_ft = 'https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'
url_desocupados = 'https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV'

# CGSSE
df_cgsse = pd.read_csv(url_cgsse, encoding='latin-1', sep=';', 
                       low_memory=False)

#Ocupados
df_ocupados=pd.read_csv(url_ocupados, encoding='latin-1',sep=';',
                        low_memory=False)

#Fuerza de trabajo
df_ft=pd.read_csv(url_ft,
                  encoding='latin-1',sep=';',low_memory=False)
#No ocupados
df_desocupados=pd.read_csv(url_desocupados,encoding='latin-1',
                           sep=';',low_memory=False)

In [33]:
codigos = ['P3271','DPTO','P6040', 'P6050', 'P3041','P2057','P6170', 'P3042','P3039']

nombres_columnas = {
    'P3271': 'sexo',
    'DPTO': 'departamento',
    'P6040': 'edad',
    'P6050': 'parentesco',
    'P3041': 'institucion',
    'P2057': 'nivel_educativo',
    'P6170': 'estado_civil',
    'P3042': 'tipo_institucion',
    'P3039': 'como_se_reconoce',
}

# Si quieres usar solo las columnas que están en df_cgsse
codigos_encontrados = [c for c in codigos if c in df_cgsse.columns]

df_seleccion = df_cgsse[codigos_encontrados].rename(columns=nombres_columnas)
df_seleccion.head(100)

,sexo,departamento,edad,parentesco,institucion,nivel_educativo,estado_civil,tipo_institucion,como_se_reconoce
0,2,8,66,1,NaN,1,2.0,5.0,2.0
1,1,8,32,3,NaN,1,2.0,5.0,1.0
2,1,8,76,1,NaN,1,2.0,3.0,1.0
3,1,8,49,9,NaN,1,2.0,1.0,1.0
4,2,8,52,13,NaN,1,2.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...
95,1,70,50,1,NaN,2,2.0,5.0,1.0
96,2,70,51,1,NaN,1,2.0,4.0,2.0
97,2,70,25,3,NaN,1,2.0,5.0,2.0
98,2,70,36,1,NaN,1,2.0,4.0,2.0
99,2,70,4,8,NaN,2,2.0,1.0,NaN

In [20]:
df_seleccion["nivel_educativo"].unique()

array([1, 2, 9])

In [21]:
df_seleccion["institucion"].unique()

array([nan,  1.,  2.])

In [35]:
# Estadísticas descriptivas por columna
estadisticas = pd.DataFrame({
    'media': df_seleccion.mean(numeric_only=True),
    'mediana': df_seleccion.median(numeric_only=True),
    'desviacion_estandar': df_seleccion.std(numeric_only=True),
    'max': df_seleccion.max(numeric_only=True),
    'min': df_seleccion.min(numeric_only=True),
    'nulos': df_seleccion.isna().sum(),
})

modas = df_seleccion.apply(lambda x: x.mode().iloc[0] if len(x.mode()) > 0 else np.nan)
estadisticas['moda'] = modas

estadisticas

,media,mediana,desviacion_estandar,max,min,nulos,moda
sexo,1.536047,2.0,0.498703,2.0,1.0,0,2.0
departamento,40.984526,44.0,25.829267,99.0,5.0,0,5.0
edad,36.631322,34.0,22.320128,103.0,0.0,0,17.0
parentesco,2.781287,2.0,2.308130,13.0,1.0,0,1.0
institucion,1.217554,1.0,0.412594,2.0,1.0,50504,1.0
nivel_educativo,1.729928,2.0,0.560649,9.0,1.0,0,2.0
estado_civil,1.736904,2.0,0.440318,2.0,1.0,1903,2.0
tipo_institucion,5.291071,5.0,2.791245,13.0,1.0,1903,3.0
como_se_reconoce,1.552239,2.0,0.498565,4.0,1.0,16735,2.0

In [37]:
# Filtrar los registros con edad menor a 25
N_df = df_seleccion[df_seleccion['edad'] < 25]

N_df.head()

,sexo,departamento,edad,parentesco,institucion,nivel_educativo,estado_civil,tipo_institucion,como_se_reconoce
10,1,8,23,1,NaN,1,2.0,4.0,1.0
11,2,8,24,2,NaN,1,2.0,4.0,2.0
12,2,8,7,3,1.0,1,1.0,3.0,NaN
13,2,8,5,3,1.0,1,1.0,2.0,NaN
14,1,8,3,3,NaN,1,2.0,1.0,NaN

In [38]:
# Estadísticas descriptivas por columna
estadisticas = pd.DataFrame({
    'media': N_df.mean(numeric_only=True),
    'mediana': N_df.median(numeric_only=True),
    'desviacion_estandar': N_df.std(numeric_only=True),
    'max': N_df.max(numeric_only=True),
    'min': N_df.min(numeric_only=True),
    'nulos': N_df.isna().sum(),
})

modas = N_df.apply(lambda x: x.mode().iloc[0] if len(x.mode()) > 0 else np.nan)
estadisticas['moda'] = modas

estadisticas

,media,mediana,desviacion_estandar,max,min,nulos,moda
sexo,1.498472,1.0,0.500008,2.0,1.0,0,1.0
departamento,40.663904,44.0,25.509120,99.0,5.0,0,47.0
edad,12.861401,13.0,6.883230,24.0,0.0,0,17.0
parentesco,4.080414,3.0,2.421460,13.0,1.0,0,3.0
institucion,1.199137,1.0,0.399364,2.0,1.0,7890,1.0
nivel_educativo,1.806145,2.0,0.463561,9.0,1.0,0,2.0
estado_civil,1.272310,1.0,0.445159,2.0,1.0,1903,1.0
tipo_institucion,4.556536,4.0,2.438903,13.0,1.0,1903,3.0
como_se_reconoce,1.521247,2.0,0.500981,3.0,1.0,16735,2.0